default_voice_key: maxime

voices:
  victor:
    display_name: "Victor"
    elevenlabs_voice_id: "GPAQQPp9dazaB2bl4zg9"
    model_id: "eleven_multilingual_v2"
    languages: ["fr"]
    voice_settings:
      stability: 0.4
      similarity_boost: 0.7
      style: 0.0
      speed: 1.1
      use_speaker_boost: true
    auto_editor_overrides:
      threshold: "0.060"
      margin: "0.04sec,0.20sec"

  # sebas:
  #   display_name: "Sebas"
  #   elevenlabs_voice_id: "5jCmrHdxbpU36l1wb3Ke"
  #   model_id: "eleven_v3"
  #   languages: ["fr"]
  #   voice_settings:
  #     stability: 1.0
  #     similarity_boost: 0.75
  #     style: 0.0
  #     speed: 1.0
  #     use_speaker_boost: true
  #   auto_editor_overrides:
  #     threshold: "0.065"
  #     margin: "0.02sec,0.12sec"

  maxime:
    display_name: "Maxime"
    elevenlabs_voice_id: "5Qfm4RqcAer0xoyWtoHC"
    model_id: "eleven_multilingual_v2"
    languages: ["fr"]
    voice_settings:
      stability: 0.50
      similarity_boost: 0.75
      style: 0.0
      speed: 1.0
      use_speaker_boost: true
    auto_editor_overrides:
      threshold: "0.05"
      margin: "0.02sec,0.12sec"

  luca:
    display_name: "Luca"
    elevenlabs_voice_id: "Ndm6bI6wo3Ycnlx1PPZS"
    model_id: "eleven_v3"
    languages: ["fr", "en"]
    voice_settings:
      stability: 1.0
      similarity_boost: 0.75
      style: 0.0
      speed: 1.0
      use_speaker_boost: true
    auto_editor_overrides:
      threshold: "0.065"
      margin: "0.02sec,0.12sec"

  nicolas_petit:
    display_name: "Nicolas Petit"
    elevenlabs_voice_id: "AmMsHJaCw4BtwV3KoUXF"
    model_id: "eleven_v3"
    languages: ["fr"]
    voice_settings:
      stability: 0.5
      similarity_boost: 0.75
      style: 0.0
      speed: 1.0
      use_speaker_boost: true
    auto_editor_overrides:
      threshold: "0.065"
      margin: "0.02sec,0.12sec"

  adam:
    display_name: "Adam"
    elevenlabs_voice_id: "93nuHbke4dTER9x2pDwE"
    model_id: "eleven_multilingual_v2"
    languages: ["fr"]
    voice_settings:
      stability: 0.5
      similarity_boost: 0.75
      style: 0.0
      speed: 1.05
      use_speaker_boost: true
    auto_editor_overrides:
      threshold: "0.065"
      margin: "0.02sec,0.12sec"

  sebastien:
    display_name: "Sébastien"
    elevenlabs_voice_id: "BUJMBsQ3Oq4cEeWSb48y"
    model_id: "eleven_v3"
    languages: ["fr"]
    voice_settings:
      stability: 0.5
      similarity_boost: 0.75
      style: 0.0
      #speed: 1.05
      speed: 1.0
      use_speaker_boost: true
    auto_editor_overrides:
      threshold: "0.065"
      margin: "0.02sec,0.12sec"
