default_music_key: montagem_batchi_cut_start_15s

music:
  credits_song_death:
    display_name: "Credits song for my death"
    file_path: "/home/sid/Projects/anime-tiktok-reproducer/assets/music/credits song for my death.wav"
    volume_db: -30

  # credits_song_death_final_boss:
  #   display_name: "Credits song for my death but im the final boss"
  #   file_path: "/home/sid/Projects/anime-tiktok-reproducer/assets/music/credits song for my death but im the final boss.wav"
  #   volume_db: -30

  lecon_particuliere:
    display_name: "La leçon particulière"
    file_path: "/home/sid/Projects/anime-tiktok-reproducer/assets/music/la lecon particuliere.wav"
    volume_db: -30
    copyright: true

  royalty:
    display_name: "Royalty"
    file_path: "/home/sid/Projects/anime-tiktok-reproducer/assets/music/royalty.wav"
    volume_db: -30

  girl_a_full_small_loop:
    display_name: "Girl A Full - Small Loop"
    file_path: "/home/sid/Projects/anime-tiktok-reproducer/assets/music/girl a full small loop.wav"
    volume_db: -30

  girl_a_cut_super_slowed:
    display_name: "Girl A Cut - Super Slowed"
    file_path: "/home/sid/Projects/anime-tiktok-reproducer/assets/music/girl a cut super slowed.wav"
    volume_db: -30

  carol_of_the_bells:
    display_name: "Carol of the Bells"
    file_path: "/home/sid/Projects/anime-tiktok-reproducer/assets/music/carol of the bells.wav"
    volume_db: -30

  night_cruising:
    display_name: "Night Cruising"
    file_path: "/home/sid/Projects/anime-tiktok-reproducer/assets/music/night cruising.wav"
    volume_db: -30
    copyright: true

  kentenshi_paranoia:
    display_name: "Kentenshi Paranoia"
    file_path: "/home/sid/Projects/anime-tiktok-reproducer/assets/music/kentenshi paranoia.wav"
    volume_db: -28

  montagem_batchi:
    display_name: "Montagem Batchi"
    file_path: "/home/sid/Projects/anime-tiktok-reproducer/assets/music/montagem batchi.wav"
    volume_db: -28

  montagem_batchi_cut_start_15s:
    display_name: "Montagem Batchi (Cut Start 15s)"
    file_path: "/home/sid/Projects/anime-tiktok-reproducer/assets/music/montagem batchi (cut start 15s).wav"
    volume_db: -25

  joyful_chess:
    display_name: "Joyful Chess"
    file_path: "/home/sid/Projects/anime-tiktok-reproducer/assets/music/joyful chess.wav"
    volume_db: -28
